### PR TITLE
remove compat_resource dependency

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@thommay there's some crazy insanity here.  the chef gem has a dev dep on cheffish which pulls in compat_resource so the chef gem is pulling in compat_resource.  i think due to the lazy require that cheffish is not pulling in compat_resource at runtime by default into chef (which would be the hella crazysauce) but we're nearly there -- and anyone pulling in cheffish /is/ always pulling in compat_resource on top of chef.

i would very much like to throw the brakes on all this.

IMO cheffish and chef_provisioning must be versioned similarly to the way that ohai is going to be versioned and we should bump the version here to 12.9.x and start to release in concert with chef core.

along with this goes the argument that we do NOT have a business requirement to make it easy for people on old versions of chef to be able to consume cheffish.

we actually have business requirements to:

- simplify our testing matrix
- provide benefit in newer versions of chef so that users have incentive to upgrade

to that extent what we're doing here with the compat_resource dep is counterproductive and solves problems we should not be solving and greatly complicated the cognitive burden of maintaining chef-client.

so the ultimate proposal here is that cheffish needs to be viewed as an extension of the chef-client core codebase and it is tightly coupled to it and need to be versioned with it (and when we get around the to chef_provisioning that Chef::ResourceBuilder monkeypatch can get terminated with extreme prejudice).

**Comment by mwrock** [comment]
I :heart: the idea of removing compat_resource from cheffish which forces us to bundle/pin compat_resource in chef-dk and then that requires users to ensure their compat_resource cookbook versions are in exact sync with the version pinned in dk and then :cry:

**Comment by jkeiser** [comment]
Isn't cheffish lazy-loaded right now in Chef? I see the reasoning here for sure :)

**Comment by mwrock** [comment]
@jkeiser if running from `chef exec` command in dk, all the bundled gems are activated at launch time

**Comment by jkeiser** [comment]
@lamont-granquist I'm assuming this is failing due to the fact that we haven't removed the references to `ChefCompat::Resource` ... if we change them to `Chef::Resource`, then we can just make a new version of `cheffish` that only works on Chef 12.5+, presumably. I'm on board with that.

**Comment by thommay** [comment]
👍

**Pull request merged**
