### PR TITLE
Fix temp hardcoding of MergedConfig api_version

### LINKED ISSUE #65: chef_server_api does not correctly handle MergedConfig
https://github.com/chef/cheffish/commit/53c8a2483f66620ba0cb8b8cdfdf797299ad62d2

This change causes a few issues:

1 - chef_server_api is expecting a MergedConfig object. When a MergedConfig object gets passed in, it dies on the merge! method because MergedConfig is not a hash. Like so:

```
NoMethodError
-------------
machine_batch[default] (/tmp/kitchen/cache/cookbooks/provisioner/providers/cluster.rb line 52) had an error:
NoMethodError: chef_client[QA1DLABTESTUBU01] (basic_chef_client::block line 132) had an error:
NoMethodError: Unexpected method merge! for MergedConfig with arguments [{:api_version=>"0"}]
```

2 - `chef_server[:options] ||= {}` is null coalescing to a hash, when it should be null coalescing to an empty MergedConfig.

As a result, since chef-provisioning has a dependency on Cheffish of `cheffish ~> 1.1`, this breaks a number of resources in the live version of chef-provisioning.

### PR DESCRIPTION
**Pull request by echohack**
Fixes #65 part 1. MergedConfig as an object is really strange to me, so please code review.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @echohack

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by echohack** [comment]
Linked up CLA to my account here.

**Comment by echohack** [comment]
just kill me, lol

**Pull request closed without merging**
