### PR TITLE
Add provides statements to avoid chef-client warnings

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by jtimberman** [comment]
LGTM :shipit:

**Comment by tyler-ball** [comment]
@stevendanna Would you mind adding it to all the resources too?  Thats the recommendation (I think)

**Comment by tyler-ball** [comment]
Also, we either need to bump the dependent version of chef up to `~> 12.3` or make this backwards compatible to versions before `provides` was supported.

Although, I can't figure out when that keyword was added....

**Comment by randomcamel** [comment]
Seems like it'd be a good idea to import the `.travis.yml` from `chef-provisioning` and run the specs against all the Chef versions.

**Comment by stevendanna** [comment]
> @stevendanna Would you mind adding it to all the resources too? Thats the recommendation (I think)

Really?  I'm starting to think that the architects of the new Resource/Provider patterns need to write canonical examples for what these need to look like.  Perhaps they already exists?

**Comment by jtimberman** [comment]
@randomcamel I don't know that those are needed in the resources. The thing that warns is when a resource doesn't have `resource_name` - as the warning messages indicate.

I *think* we're okay because of lines like this:

https://github.com/chef/cheffish/blob/ssd/warning/lib/chef/resource/chef_acl.rb#L5

Paging @jkeiser and @lamont-granquist

**Comment by jkeiser** [comment]
Yeah, I'm surprised `self.resource_name = 'blah'` is not clearing the warning for the LWRP. That sounds like I missed a spot for warning clearage.

**Comment by tyler-ball** [comment]
I'm going to go ahead and merge this - we threw out a bunch of improvement ideas but those all need to be filed as new bugs.  Lets not scope creep this.  Thanks @stevendanna !

**Pull request merged**
