### PR TITLE
remove cheffish-rspec (DO NOT MERGE YET)

### PR DESCRIPTION
**Pull request by lamont-granquist**
⚠️ 	we can't merge this until we do something about chef/chef's integration tests that use this ⚠️ 	

- this appears to not be used in cheffish
- this appears to not be tested in cheffish
- it appears all that uses this is chef/chef internally even
  though its parked for some mysterious reason in the cheffish
  gem.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
oh nevermind, i wasn't bundle'ing correctly.

**Comment by tas50** [comment]
This is a beautiful thing to see finally happening

**Comment by lamont-granquist** [comment]
Yeah I think I've got to do some kind of dance to move it into chef/chef and then make cheffish depend on chef/chef and then try to simplify it once the code lands in chef/chef

**Comment by tas50** [comment]
I'd consider it a win if all we did was forklift it. Then we'd at least kill of a silly dep

**Pull request closed without merging**
